
module.exports = (grunt)->
  version = ->
    grunt.file.readJSON("package.json").version
  version_text = ->
    "v#{version()}"

  repo = "https://github.com/dylan/SVGTracer.js"

  grunt.initConfig
    pkg: grunt.file.readJSON("package.json")
    repo: repo

    comments: """
/*
// <%= pkg.name %>
// v<%= pkg.version %>
// Built on <%= grunt.template.today("yyyy-mm-dd") %>
// Full source at <%= repo %>
//
// MIT License, <%= repo %>/blob/master/LICENSE
// This file is generated by `grunt build` do not edit it by hand.
*/\n
"""
    minified_comments: "/* <%= pkg.name %> v<%= pkg.version %>, MIT License <%= repo %>/blob/master/LICENSE */"

    connect:
      server:
        options:
          hostname: '*'
          port: 3000
          base: '.'

    open:
      all:
        path: 'http://localhost:<%= connect.server.options.port%>/example/index.html'

    coffee:
      compile:
        options:
          bare: true
          sourceMap: true
        files:
          'dist/SVGTracer.js': 'src/**/*.coffee'

    uglify:
      options:
        mangle:
          except: ['node', 'SVGTracer']
        banner: "<%= minified_comments %>"

      minify:
        files:
          'dist/SVGTracer.min.js': ['dist/SVGTracer.js']

    coffeelint:
      source: 'coffee/**/*.coffee'

    clean:
      dist: ['dist/*.js','dist/*.map']

    watch:
      scripts:
        files: ['src/**/*.coffee','example/*.html','example/*.css']
        tasks: ['build']
        options:
          livereload: true
          nospawn: true

  grunt.loadNpmTasks 'grunt-contrib-connect'
  grunt.loadNpmTasks 'grunt-open'
  grunt.loadNpmTasks 'grunt-notify'
  grunt.loadNpmTasks 'grunt-contrib'
  grunt.loadNpmTasks 'grunt-coffeelint'

  grunt.registerTask 'default', ['build']
  grunt.registerTask 'build',   ['coffeelint','coffee','uglify']
  grunt.registerTask 'server',  ['build','connect','open','watch']
